### ISSUE TITLE
upgrade Python version at least > 3.9, hopefully 3.12

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-container#14]
following https://github.com/oda-hub/oda_api/pull/279#pullrequestreview-2250691273

**Comment by volodymyrss** [comment]
I propose that @burnout87 does it to better keep track of the code dependencies.

**Comment by burnout87** [comment]
I guess you mean restrict to use python versions to only `3.10` and `3.11`...?

**Comment by volodymyrss** [comment]
It's fixed container environment and it has a single version, currently [3.8](https://github.com/oda-hub/dispatcher-container/blob/e2efa0289c6692eeb32f7d2036cf2bae2b7b46ff/Dockerfile#L1). 

Since we are dropping support of 3.8, we should increase the version in the container to the largest version we can support. If 3.12 works it's even better. Probably 3.12.

Doing this might lead to dependency issues which need to be reconciled.

**Comment by volodymyrss** [comment]
But this means rebuilding osa+heasoft with new python which might not work easily.

We only need them for xspec functionality I guess.

Would you try building new OSA+Heasoft by upgrading https://github.com/ISDC-integral/osa-python-docker/? It's useful anyway.

If it does not work so easily, we can replace or drop the xspec functionality.

**Comment by burnout87** [comment]
> 
> Would you try building new OSA+Heasoft by upgrading https://github.com/ISDC-integral/osa-python-docker/? It's useful anyway.
> 
I need permission on that repo to make a PR

**Comment by volodymyrss** [comment]
> > Would you try building new OSA+Heasoft by upgrading https://github.com/ISDC-integral/osa-python-docker/? It's useful anyway.
> 
> I need permission on that repo to make a PR

Did you make a fork?

**Comment by burnout87** [comment]
> > > Would you try building new OSA+Heasoft by upgrading https://github.com/ISDC-integral/osa-python-docker/? It's useful anyway.
> > 
> > 
> > I need permission on that repo to make a PR
> 
> Did you make a fork?

no I just cloned it, I'll make a fork...

**Comment by volodymyrss** [comment]
> > > > Would you try building new OSA+Heasoft by upgrading https://github.com/ISDC-integral/osa-python-docker/? It's useful anyway.
> > > 
> > > 
> > > I need permission on that repo to make a PR
> > 
> > 
> > Did you make a fork?
> 
> no I just cloned it, I'll make a fork...

Ok! Actually looks like the latest version is built by Carlo and it's with 3.10. We should check it.

**Comment by burnout87** [comment]
it fails for `xspec`

https://github.com/oda-hub/dispatcher-container/actions/runs/10521973707/job/29153665851?pr=16

**Comment by volodymyrss** [comment]
> it fails for `xspec`
> 
> https://github.com/oda-hub/dispatcher-container/actions/runs/10521973707/job/29153665851?pr=16

I think the container should support xspec.  If not, please make an issue on osa-python-docker and assign to @ferrigno .

**Comment by burnout87** [comment]
and it builds without xpec

**Comment by volodymyrss** [comment]
> and it builds without xpec

What do you mean?

**Comment by burnout87** [comment]
By commenting the lines:

https://github.com/oda-hub/dispatcher-container/blob/c0953ee0ec4bdb1f977cf64b4dd6fa271a20c03b/Dockerfile#L13-L14

it was successfully building

**Comment by burnout87** [comment]
To be more precise:

With the following version of the container: `integralsw/osa-python:11.2-2-g667521a3-20220403-190332-refcat-43.0-heasoft-6.33-python-3.10.11`

It does not build

With this one: `integralsw/osa-python:11.2-2-g667521a3-20220403-190332-refcat-43.0-heasoft-6.32.1-python-3.10.11`

it does build

It looks like the difference between is the heasoft version, is there something else?

**Comment by ferrigno** [comment]
It should not be anything different but heasoft. I might have corrected
issues with the latter version

Il Ven 23 Ago 2024, 10:43 Gabriele Barni ***@***.***> ha
scritto:

**Comment by volodymyrss** [comment]
We don't really care about the effect of the heasoft version increase here. Better to keep the old one, if anything. 
So if it builds one, let's keep it!

**Comment by burnout87** [comment]
> 
> I think the container should support xspec. If not, please make an issue on osa-python-docker and assign to @ferrigno .

https://github.com/ISDC-integral/osa-python-docker/issues/4#issuecomment-2306682415
