### ISSUE TITLE
Consider adding timestamp to the container's tag

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-container#7]
This allows [image automation](https://fluxcd.io/flux/guides/image-update/) in Flux. 
Same for other containers, built with unige's gitlab CI

**Comment by dsavchenko** [comment]
@volodymyrss can you do it? To not accidentally break something, you can leave everything as it is, just add another duplicate tag with timestamp.

**Comment by volodymyrss** [comment]
would tags like this work https://hub.docker.com/layers/odahub/dispatcher/230713-195737/images/sha256-efc51ee51c7316a69d77448a53c30f7358c51a8db6afe030370b6d979115796a?context=explore ?

**Comment by dsavchenko** [comment]
Yes, any kind off sortable tags (or it's part) will work. Thanks

**Comment by volodymyrss** [comment]
As of now this will be the case. The other ones will remain so I hope they do not affect your sorting. Please reopen if insufficient.
