### ISSUE TITLE
container start failing

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-container#8]

**Comment by burnout87** [comment]
https://github.com/oda-hub/dispatcher-app/pull/587

**Comment by burnout87** [comment]
I could reproduce the error locally by installing the same `flask` version as I saw in the sentry issues  (https://cdci.sentry.io/issues/4438782485/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4 , https://cdci.sentry.io/issues/4463795248/events/d29768ae199e426c80e52a7cdbcc1b8d/?project=1467382).

As frozen within the dispatcher requirements, it should be `>=2.0.3`, but the `1.1.2` is installed.

**Comment by volodymyrss** [comment]
> I could reproduce the error locally by installing the same `flask` version as I saw in the sentry issues (https://cdci.sentry.io/issues/4438782485/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4 , https://cdci.sentry.io/issues/4463795248/events/d29768ae199e426c80e52a7cdbcc1b8d/?project=1467382).
> 
> As frozen within the dispatcher requirements, it should be `>=2.0.3`, but the `1.1.2` is installed.

Container build needs to be adapted.

**Comment by burnout87** [comment]
> > I could reproduce the error locally by installing the same `flask` version as I saw in the sentry issues (https://cdci.sentry.io/issues/4438782485/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4 , https://cdci.sentry.io/issues/4463795248/events/d29768ae199e426c80e52a7cdbcc1b8d/?project=1467382).
> > As frozen within the dispatcher requirements, it should be `>=2.0.3`, but the `1.1.2` is installed.
> 
> Container build needs to be adapted.

Creating a fix
